import type { BodyTemplate } from "./types.js";

export const humanoidTemplate: BodyTemplate = {
  id: "humanoid",
  name: "Humanoid",
  parts: [
    // === BODY (main torso) ===
    {
      name: "body",
      primitive: "capsule",
      position: [0, 0.75, 0],
      rotation: [0, 0, 0],
      scale: [0.45, 0.45, 0.38],
      colorRole: "body",
      material: { roughness: 0.7, metalness: 0.05, flatShading: true },
    },
    // === HEAD ===
    {
      name: "head",
      primitive: "sphere",
      position: [0, 1.45, 0],
      rotation: [0, 0, 0],
      scale: [0.32, 0.30, 0.30],
      colorRole: "body",
      material: { roughness: 0.7, metalness: 0.05, flatShading: true },
      animatable: { type: "bob", speed: 0.8, amplitude: 0.015 },
      children: [
        // Eyes (children of head — positions relative to head center)
        {
          name: "eye-left",
          primitive: "sphere",
          position: [-0.4, 0.1, 0.75],
          rotation: [0, 0, 0],
          scale: [0.3, 0.35, 0.18],
          colorRole: "eyeWhite",
          material: { roughness: 0.3, metalness: 0.0, flatShading: false },
          children: [{
            name: "pupil-left",
            primitive: "sphere",
            position: [0, 0, 0.45],
            rotation: [0, 0, 0],
            scale: [0.5, 0.55, 0.35],
            colorRole: "eye",
            material: { roughness: 0.2, metalness: 0.0, flatShading: false },
          }],
        },
        {
          name: "eye-right",
          primitive: "sphere",
          position: [0.4, 0.1, 0.75],
          rotation: [0, 0, 0],
          scale: [0.3, 0.35, 0.18],
          colorRole: "eyeWhite",
          material: { roughness: 0.3, metalness: 0.0, flatShading: false },
          children: [{
            name: "pupil-right",
            primitive: "sphere",
            position: [0, 0, 0.45],
            rotation: [0, 0, 0],
            scale: [0.5, 0.55, 0.35],
            colorRole: "eye",
            material: { roughness: 0.2, metalness: 0.0, flatShading: false },
          }],
        },
        // Mouth
        {
          name: "mouth",
          primitive: "sphere",
          position: [0, -0.35, 0.7],
          rotation: [0, 0, 0],
          scale: [0.35, 0.1, 0.12],
          colorRole: "mouth",
          material: { roughness: 0.8, metalness: 0.0, flatShading: true },
        },
        // Ears
        {
          name: "ear-left",
          primitive: "cone",
          position: [-0.7, 0.35, 0],
          rotation: [0, 0, 0.4],
          scale: [0.18, 0.28, 0.15],
          colorRole: "accent",
          material: { roughness: 0.8, metalness: 0.1, flatShading: true },
          animatable: { type: "wiggle", speed: 1.2, amplitude: 0.08 },
        },
        {
          name: "ear-right",
          primitive: "cone",
          position: [0.7, 0.35, 0],
          rotation: [0, 0, -0.4],
          scale: [0.18, 0.28, 0.15],
          colorRole: "accent",
          material: { roughness: 0.8, metalness: 0.1, flatShading: true },
          animatable: { type: "wiggle", speed: 1.2, amplitude: 0.08 },
        },
      ],
    },
    // === ARMS ===
    {
      name: "arm-left",
      primitive: "capsule",
      position: [-0.5, 0.85, 0],
      rotation: [0, 0, 0.3],
      scale: [0.08, 0.18, 0.08],
      colorRole: "body",
      material: { roughness: 0.7, metalness: 0.05, flatShading: true },
      animatable: { type: "sway", speed: 1.0, amplitude: 0.12 },
    },
    {
      name: "arm-right",
      primitive: "capsule",
      position: [0.5, 0.85, 0],
      rotation: [0, 0, -0.3],
      scale: [0.08, 0.18, 0.08],
      colorRole: "body",
      material: { roughness: 0.7, metalness: 0.05, flatShading: true },
      animatable: { type: "sway", speed: 1.0, amplitude: 0.12 },
    },
    // === LEGS ===
    {
      name: "leg-left",
      primitive: "capsule",
      position: [-0.18, 0.22, 0],
      rotation: [0, 0, 0],
      scale: [0.1, 0.18, 0.1],
      colorRole: "accent",
      material: { roughness: 0.9, metalness: 0.05, flatShading: true },
      children: [{
        name: "foot-left",
        primitive: "box",
        position: [0, -0.7, 0.15],
        rotation: [0, 0, 0],
        scale: [0.85, 0.3, 1.2],
        colorRole: "accent",
        material: { roughness: 0.9, metalness: 0.0, flatShading: true },
      }],
    },
    {
      name: "leg-right",
      primitive: "capsule",
      position: [0.18, 0.22, 0],
      rotation: [0, 0, 0],
      scale: [0.1, 0.18, 0.1],
      colorRole: "accent",
      material: { roughness: 0.9, metalness: 0.05, flatShading: true },
      children: [{
        name: "foot-right",
        primitive: "box",
        position: [0, -0.7, 0.15],
        rotation: [0, 0, 0],
        scale: [0.85, 0.3, 1.2],
        colorRole: "accent",
        material: { roughness: 0.9, metalness: 0.0, flatShading: true },
      }],
    },
    // === TAIL ===
    {
      name: "tail",
      primitive: "capsule",
      position: [0, 0.5, -0.35],
      rotation: [0.6, 0, 0],
      scale: [0.06, 0.15, 0.06],
      colorRole: "accent",
      material: { roughness: 0.8, metalness: 0.1, flatShading: true },
      animatable: { type: "sway", speed: 2.0, amplitude: 0.2 },
    },
    // === ACCESSORIES (optional) ===
    {
      name: "hat",
      primitive: "cylinder",
      position: [0, 1.78, 0],
      rotation: [0, 0, 0],
      scale: [0.35, 0.15, 0.35],
      colorRole: "accessory",
      material: { roughness: 0.6, metalness: 0.1, flatShading: true },
      optional: true,
      accessoryGroup: "hat",
    },
    {
      name: "scarf",
      primitive: "torus",
      position: [0, 1.15, 0],
      rotation: [1.5708, 0, 0],
      scale: [0.32, 0.32, 0.06],
      colorRole: "accessory",
      material: { roughness: 0.9, metalness: 0.0, flatShading: true },
      optional: true,
      accessoryGroup: "scarf",
    },
    {
      name: "backpack",
      primitive: "box",
      position: [0, 0.8, -0.35],
      rotation: [0, 0, 0],
      scale: [0.25, 0.3, 0.15],
      colorRole: "accessory",
      material: { roughness: 0.8, metalness: 0.05, flatShading: true },
      optional: true,
      accessoryGroup: "backpack",
    },
    {
      name: "glasses",
      primitive: "torus",
      position: [0, 1.47, 0.25],
      rotation: [1.5708, 0, 0],
      scale: [0.28, 0.08, 0.12],
      colorRole: "accessory",
      material: { roughness: 0.3, metalness: 0.5, flatShading: true },
      optional: true,
      accessoryGroup: "glasses",
    },
  ],
};
